### ISSUE TITLE
Works with ruby 2.6 and not with ruby 2.7

### ISSUE THREAD

**Issue by noraj** [hendrixfan/triangle#4]
I do not really understand why but it works well with ruby 2.6.0 and crashes with ruby 2.70.

```ruby
require 'triangle_pattern'

pattern = TrianglePattern.generate(
  colors: ["#edf8fb", "#b2e2e2", "#66c2a4", "#2ca25f", "#006d2c"],
  width: 1920,
  height: 1080,
  cell_size: 75,
  variance: 0.75,
  seed: 135
)
```

```
noraj@devarch ~/Pictures/triangle_patterns » rbenv shell 2.6.0
noraj@devarch ~/Pictures/triangle_patterns » ruby generate.rb 
noraj@devarch ~/Pictures/triangle_patterns » rbenv shell 2.7.0                                        
noraj@devarch ~/Pictures/triangle_patterns » gem list | grep triangle      
triangle_pattern (0.2.2)
noraj@devarch ~/Pictures/triangle_patterns » ruby generate.rb              
Traceback (most recent call last):
        2: from generate.rb:1:in `<main>'
        1: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- triangle_pattern (LoadError)
        12: from generate.rb:1:in `<main>'
        11: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        10: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
         9: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
         8: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/triangle_pattern-0.2.2/lib/triangle_pattern.rb:7:in `<top (required)>'
         7: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         6: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         5: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/gradient-0.5.1/lib/gradient.rb:8:in `<top (required)>'
         4: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         3: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         2: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/gradient-0.5.1/lib/gradient/svg.rb:1:in `<top (required)>'
         1: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- scanf (LoadError)
```

**Comment by hendrixfan** [comment]
It's a Issue compatability Issue with the [gradient gem](https://github.com/zeeraw/gradient) and ruby 2.7.
I opend an Issue https://github.com/zeeraw/gradient/issues/7

**Comment by hendrixfan** [comment]
fixed in https://github.com/hendrixfan/triangle/commit/150c3694b86f868021a4f1506c57506bc485c5b5
